### ISSUE TITLE
Publish new gem version

### ISSUE THREAD

**Issue by ilya-konanykhin** [huwtl/secure_yaml#5]
Hello. Would you be so kind to update the gem version and publish it on Rubygems.org, like the previous version? It'll be cool to update the gem the regular way, without sticking to the github master branch.

**Comment by rennhak** [comment]
+1

**Comment by huwtl** [comment]
v2.0.2 has been published to rubygems.org, any issues then let me know

**Comment by ilya-konanykhin** [comment]
Sweet! Thank you very much.

**Comment by rennhak** [comment]
Thank you for the quick response!
